[package]
name = "scrapt-xmls"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
zip = "0.6"
clap = { version = "4.5", features = ["derive"] }
walkdir = "2.5"
rayon = "1.11.0"
tempfile = "3.21.0"
regex = "1.11.2"
dirs = "6.0.0"
